### PR TITLE
OIDCPublicKeyFiles update

### PR DESCRIPTION
**Pull request by absynth76**
add the possibility to use a public key instead of a certificate for the parameter in subject.

added an alpine dockerfile =~ 20MB

### CODE REVIEW

**Comment by zandbelt** [comment]
I like it, especially the fact that it comes with a test! I'll review some more and merge soon, thanks!

**Comment by zandbelt** [comment]
Could you add something to the ChangeLog as well?

**Comment by zandbelt** [comment]
@absynth76 looks like we can ditch https://github.com/zmartzone/mod_auth_openidc/blob/master/test/private.pem ?

**Comment by absynth76** [comment]
> 
> 
> @absynth76 looks like we can ditch https://github.com/zmartzone/mod_auth_openidc/blob/master/test/private.pem ?

It's only a sample for test purpose, don't hesitate to drop it if you don't like, however there is an associated test with it. It was only there to validate the code change, a better approach could have to generate a keypair at each test but it would have be more code. Not to use in prod for sure :)

**Pull request merged**
